# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Raphael/Documents/info0402

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Raphael/Documents/info0402

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Raphael/Documents/info0402/CMakeFiles /mnt/c/Users/Raphael/Documents/info0402/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Raphael/Documents/info0402/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QtProject

# Build rule for target.
QtProject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QtProject
.PHONY : QtProject

# fast build rule for target.
QtProject/fast:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/build
.PHONY : QtProject/fast

src/.old-main.o: src/.old-main.c.o

.PHONY : src/.old-main.o

# target to build an object file
src/.old-main.c.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/.old-main.c.o
.PHONY : src/.old-main.c.o

src/.old-main.i: src/.old-main.c.i

.PHONY : src/.old-main.i

# target to preprocess a source file
src/.old-main.c.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/.old-main.c.i
.PHONY : src/.old-main.c.i

src/.old-main.s: src/.old-main.c.s

.PHONY : src/.old-main.s

# target to generate assembly for a file
src/.old-main.c.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/.old-main.c.s
.PHONY : src/.old-main.c.s

src/catch.o: src/catch.cpp.o

.PHONY : src/catch.o

# target to build an object file
src/catch.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/catch.cpp.o
.PHONY : src/catch.cpp.o

src/catch.i: src/catch.cpp.i

.PHONY : src/catch.i

# target to preprocess a source file
src/catch.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/catch.cpp.i
.PHONY : src/catch.cpp.i

src/catch.s: src/catch.cpp.s

.PHONY : src/catch.s

# target to generate assembly for a file
src/catch.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/catch.cpp.s
.PHONY : src/catch.cpp.s

src/counter/Counter.o: src/counter/Counter.cpp.o

.PHONY : src/counter/Counter.o

# target to build an object file
src/counter/Counter.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/counter/Counter.cpp.o
.PHONY : src/counter/Counter.cpp.o

src/counter/Counter.i: src/counter/Counter.cpp.i

.PHONY : src/counter/Counter.i

# target to preprocess a source file
src/counter/Counter.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/counter/Counter.cpp.i
.PHONY : src/counter/Counter.cpp.i

src/counter/Counter.s: src/counter/Counter.cpp.s

.PHONY : src/counter/Counter.s

# target to generate assembly for a file
src/counter/Counter.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/counter/Counter.cpp.s
.PHONY : src/counter/Counter.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map/rb_tree.o: src/map/rb_tree.c.o

.PHONY : src/map/rb_tree.o

# target to build an object file
src/map/rb_tree.c.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/map/rb_tree.c.o
.PHONY : src/map/rb_tree.c.o

src/map/rb_tree.i: src/map/rb_tree.c.i

.PHONY : src/map/rb_tree.i

# target to preprocess a source file
src/map/rb_tree.c.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/map/rb_tree.c.i
.PHONY : src/map/rb_tree.c.i

src/map/rb_tree.s: src/map/rb_tree.c.s

.PHONY : src/map/rb_tree.s

# target to generate assembly for a file
src/map/rb_tree.c.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/map/rb_tree.c.s
.PHONY : src/map/rb_tree.c.s

src/test/Algorithm.o: src/test/Algorithm.cpp.o

.PHONY : src/test/Algorithm.o

# target to build an object file
src/test/Algorithm.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/Algorithm.cpp.o
.PHONY : src/test/Algorithm.cpp.o

src/test/Algorithm.i: src/test/Algorithm.cpp.i

.PHONY : src/test/Algorithm.i

# target to preprocess a source file
src/test/Algorithm.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/Algorithm.cpp.i
.PHONY : src/test/Algorithm.cpp.i

src/test/Algorithm.s: src/test/Algorithm.cpp.s

.PHONY : src/test/Algorithm.s

# target to generate assembly for a file
src/test/Algorithm.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/Algorithm.cpp.s
.PHONY : src/test/Algorithm.cpp.s

src/test/BSTree.o: src/test/BSTree.cpp.o

.PHONY : src/test/BSTree.o

# target to build an object file
src/test/BSTree.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/BSTree.cpp.o
.PHONY : src/test/BSTree.cpp.o

src/test/BSTree.i: src/test/BSTree.cpp.i

.PHONY : src/test/BSTree.i

# target to preprocess a source file
src/test/BSTree.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/BSTree.cpp.i
.PHONY : src/test/BSTree.cpp.i

src/test/BSTree.s: src/test/BSTree.cpp.s

.PHONY : src/test/BSTree.s

# target to generate assembly for a file
src/test/BSTree.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/BSTree.cpp.s
.PHONY : src/test/BSTree.cpp.s

src/test/List.o: src/test/List.cpp.o

.PHONY : src/test/List.o

# target to build an object file
src/test/List.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/List.cpp.o
.PHONY : src/test/List.cpp.o

src/test/List.i: src/test/List.cpp.i

.PHONY : src/test/List.i

# target to preprocess a source file
src/test/List.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/List.cpp.i
.PHONY : src/test/List.cpp.i

src/test/List.s: src/test/List.cpp.s

.PHONY : src/test/List.s

# target to generate assembly for a file
src/test/List.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/List.cpp.s
.PHONY : src/test/List.cpp.s

src/test/Multimap.o: src/test/Multimap.cpp.o

.PHONY : src/test/Multimap.o

# target to build an object file
src/test/Multimap.cpp.o:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/Multimap.cpp.o
.PHONY : src/test/Multimap.cpp.o

src/test/Multimap.i: src/test/Multimap.cpp.i

.PHONY : src/test/Multimap.i

# target to preprocess a source file
src/test/Multimap.cpp.i:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/Multimap.cpp.i
.PHONY : src/test/Multimap.cpp.i

src/test/Multimap.s: src/test/Multimap.cpp.s

.PHONY : src/test/Multimap.s

# target to generate assembly for a file
src/test/Multimap.cpp.s:
	$(MAKE) -f CMakeFiles/QtProject.dir/build.make CMakeFiles/QtProject.dir/src/test/Multimap.cpp.s
.PHONY : src/test/Multimap.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... QtProject"
	@echo "... edit_cache"
	@echo "... src/.old-main.o"
	@echo "... src/.old-main.i"
	@echo "... src/.old-main.s"
	@echo "... src/catch.o"
	@echo "... src/catch.i"
	@echo "... src/catch.s"
	@echo "... src/counter/Counter.o"
	@echo "... src/counter/Counter.i"
	@echo "... src/counter/Counter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map/rb_tree.o"
	@echo "... src/map/rb_tree.i"
	@echo "... src/map/rb_tree.s"
	@echo "... src/test/Algorithm.o"
	@echo "... src/test/Algorithm.i"
	@echo "... src/test/Algorithm.s"
	@echo "... src/test/BSTree.o"
	@echo "... src/test/BSTree.i"
	@echo "... src/test/BSTree.s"
	@echo "... src/test/List.o"
	@echo "... src/test/List.i"
	@echo "... src/test/List.s"
	@echo "... src/test/Multimap.o"
	@echo "... src/test/Multimap.i"
	@echo "... src/test/Multimap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

